### PR TITLE
Timeout: save should stop and fail tests if the timeout is reached

### LINKED ISSUE #274: Timeout: save should stop and fail tests if the timeout is reached
We need to add a configurable timeout to save tests. If test runs more than N seconds, test should be stopped and marked as failed

### PR DESCRIPTION
**Pull request by Cheshiriks**
What's done:
* Added timeout for tests
Closes #274

### CODE REVIEW

**Review by petertrr — APPROVED** [review]

File: save-core/src/commonNonJsTest/kotlin/org/cqfn/save/core/integration/ClassicWarnTest.kt [hunk 1]
```diff
@@ -82,13 +84,13 @@ class ClassicWarnTest {
         )
     }
 
-    @Test
```
Comment (kgevorkyan) [inline save-core/src/commonNonJsTest/kotlin/org/cqfn/save/core/integration/ClassicWarnTest.kt]: You removed annotation here
